### ISSUE TITLE
GitHub Action for CI

### ISSUE THREAD

**Issue by TYoungSL** [StirlingLabs/BigBuffers#7]
Need to build via cmake for windows, mac and linux.

Just need to build the `bufc` cmake target.

Also need to use `dotnet` to build `net/BigBuffers.sln` for release. (Maybe `cd net` then build.)

It will need access to BigSpans in the the GitHub-StirlingLabs package source.

I think @Rjvs is going to make BigSpans public, so it might not need a permissioned token.

**Comment by Rjvs** [comment]
BigSpans is public.

**Comment by Rjvs** [comment]
@ilkerhalil this will be a blocker for us early next week, so should take precedence over other experiments.

**Comment by ilkerhalil** [comment]
@Rjvs I'm starting right now.

**Comment by Rjvs** [comment]
For avoidance of confusion; we only want to build C# language compatibility for now. We will add Go later and perhaps some other languages in the future if that becomes necessary but we are dropping support for lots of other languages (unless there is community support for them).

Likewise, we do not want to support all of the various CI options that have been used in the past. Just GitHub Actions (no Travis, etc). Once any information that is useful has been derived from the old CI files, they should be deleted.
